### ISSUE TITLE
Answer bar

### ISSUE THREAD

**Issue by Gueazy** [Quip13/No-Distractions-Full-Screen#10]
Hello! Thank for the addon, the update is super cool!!!
But I have a problem with my answer buttons, when reviewing I only see the "correct" button, and not the others...

<img width="806" alt="Buttons" src="https://user-images.githubusercontent.com/47318795/77915934-99412400-7298-11ea-9de0-844123f445f1.png">

**Comment by Quip13** [comment]
Interesting - it looks like they're there just the styling isn't applying. Are you using any other styling addons?
All the different addon stylings pile on top of each other so it's hard to know what the culprit is. If you can narrow it down to which addon is conflicting, I can try to replicate it

**Comment by Gueazy** [comment]
I dont think so, i just use king buttons
This is my addons

<img width="732" alt="Capture d’écran 2020-03-30 à 9 08 15 PM" src="https://user-images.githubusercontent.com/47318795/77951581-95c69080-72ca-11ea-83b7-06c4ffc4e7b8.png">

**Comment by Quip13** [comment]
It might be a language thing then - I'll look into a multilingual solution

**Comment by Gueazy** [comment]
Thank you!!!!

**Comment by Quip13** [comment]
Actually can you verify that it works in english?

**Comment by Gueazy** [comment]
It works, you were right!

<img width="777" alt="Capture d’écran 2020-03-30 à 9 16 09 PM" src="https://user-images.githubusercontent.com/47318795/77952283-ae837600-72cb-11ea-8d7e-38566407e345.png">

**Comment by Gueazy** [comment]
If I can help you for the french tell me

**Comment by Quip13** [comment]
Okay just updated it to have multilingual support! Thanks for the report
Let me know if you're still having issues
