### ISSUE TITLE
Affects javascript on card styling

### ISSUE THREAD

**Issue by AnKingMed** [Quip13/No-Distractions-Full-Screen#11]
This isn't a serious issue, but if you know a solution I'd definitely appreciate it.  I have a "Cloze one-by-one" card type that allows you to have a card with all c1 and then open the clozes one at a time.  I've shared this online and I believe it gets used by quite a few people.   I've noticed it doesn't work with this add-on and I can't figure out why.

It doesn't work in normal mode if I have enabled "cursor hide" and it doesn't work in the no distractions mode no matter what I try. I'm guessing your add-on overrides the script or something?   If there is a way to make them both compatible I'd really appreciate it (and it would save me a headache from everyone emailing me saying the card type isn't working since I just told everyone to use this add-on in my video about the Custom Background add-on I just released :)

Here's the script I put on the back template of the note:

<script>
//SHORTCUT TO REVEAL CLOZES
var shortcut = 'n'
//SHORTCUT END
</script>

<script>
var clozes = document.getElementsByClassName("cloze");
var clr = window.getComputedStyle(clozes[0]).color;
var bg = window.getComputedStyle(clozes[0]).background;
for (i=1; i<clozes.length; ++i) {
  clozes[i].style.background = clr;
  clozes[i].onclick = function() {this.style.background=bg ;}
}
</script>

<script>
    const clozes = [...document.querySelectorAll(".cloze")];
    if (clozes.length) {
        const cloze_color = window.getComputedStyle(clozes[0]).color;
        const cloze_bg_color = window.getComputedStyle(clozes[0]).backgroundColor;
        clozes.slice(1).forEach((item) => {
            item.style.backgroundColor = cloze_color;
            item.addEventListener("click", () => {
                item.style.backgroundColor = cloze_bg_color;
            });
        });
//USER CUSTOMIZATION event.key

        document.addEventListener("keydown", (event) => {
            if (event.key == shortcut) {
                clozes.slice(1).some((item) => {
                    if (item.style.backgroundColor != cloze_bg_color) {
                        item.style.backgroundColor = cloze_bg_color;
                        return true;
                    }
                })
            }
        });
    }
</script>

**Comment by Quip13** [comment]
Happy to help - and thanks for the plug! The stuff you're doing with Anking v6 is fire - I wish I had stuff like that when I took step

Unfortunately that script doesn't work for me even with the addon disabled - it gives me a syntax error. Seems like there's an extra <script> in the for loop

**Comment by AnKingMed** [comment]
I might have copied it wrong.  I'll copy it again here and attach the note type if you want to try it in a new profile (the key is currently set to "n" to reveal them one at a time but you should also be able to click on the boxes:

`<script>
var clozes = document.getElementsByClassName("cloze");
var clr = window.getComputedStyle(clozes[0]).color;
var bg = window.getComputedStyle(clozes[0]).background;
for (i=1; i<clozes.length; ++i) {
  clozes[i].style.background = clr;
  clozes[i].onclick = function() {this.style.background=bg ;}
}
</script>

<script>
    const clozes = [...document.querySelectorAll(".cloze")];
    if (clozes.length) {
        const cloze_color = window.getComputedStyle(clozes[0]).color;
        const cloze_bg_color = window.getComputedStyle(clozes[0]).backgroundColor;
        clozes.slice(1).forEach((item) => {
            item.style.backgroundColor = cloze_color;
            item.addEventListener("click", () => {
                item.style.backgroundColor = cloze_bg_color;
            });
        });
//USER CUSTOMIZATION event.key

        document.addEventListener("keydown", (event) => {
            if (event.key == n) {
                clozes.slice(1).some((item) => {
                    if (item.style.backgroundColor != cloze_bg_color) {
                        item.style.backgroundColor = cloze_bg_color;
                        return true;
                    }
                })
            }
        });
    }
</script>`

[Cloze1by1.apkg.zip](https://github.com/Quip13/No-Distractions-Full-Screen/files/4409507/Cloze1by1.apkg.zip)

**Comment by Quip13** [comment]
It seems to work for me:
![G0Gualrte2](https://user-images.githubusercontent.com/11655350/78038047-56d02380-733a-11ea-9f0d-24a82986dfb2.gif)

**Comment by AnKingMed** [comment]
I think I figured it out.  When I go to the next card, it auto selects the "good" button instead of anki's default which auto selects the card itself.   I can tell because when no distractions is enabled, there is a blue outline around the show answer and good button.  If I click the card itself, then I can use the shortcut.  Any idea why that is?

**Comment by Quip13** [comment]
Oh it does that for me even with all addons disabled. If I recall correctly from the source code, Anki defaults to the bottom and only focuses the main screen when it's a fill in the blank card

**Comment by AnKingMed** [comment]
Now that I think about it, it's probably because I have the Refocus card when reviewing add-on, so that must be where the conflict is

**Comment by Quip13** [comment]
hmm okay I'll see if I can make it compatible

**Comment by Quip13** [comment]
Alright I think I fixed the issue - let me know if it works for you

**Comment by AnKingMed** [comment]
Works great now! Thanks!

**Comment by Quip13** [comment]
np - thanks for the bug report!
