### ISSUE TITLE
Addon doesn't scroll with overflow when full screen

### ISSUE THREAD

**Issue by skiplesions** [Quip13/No-Distractions-Full-Screen#12]
I have this code in my card template which makes my card scroll down when I flip and the answer has a lot of information on it. When I have fullscreen enabled it doesn't work for some reason.

html {
  overflow:   scroll;
   scroll-behavior: smooth;
}
::-webkit-scrollbar {
    width: 0px;
    scroll-behavior: smooth;
    background: transparent; /* make scrollbar transparent */
}

**Comment by Quip13** [comment]
Interesting - I'm not sure either - i'll have to investigate
Curiously if I delete scroll-behavior:smooth it works, albeit a bit ugly

**Comment by Quip13** [comment]
Argh Javascript's asynchronous behavior is killing me and I'm not sure how to fix it -  I'm a newbie to all this - but here's a kind of hacky workaround:

Put this at the end of your back template:
`<script>
setTimeout(function(){ 
            var e = $("#answer");
            if (e[0]) {
                e[0].scrollIntoView();
            }
 }, 10);
</script>`

I'll tinker a bit to look for a more robust solution that doesn't require custom scripts

**Comment by Quip13** [comment]
Unfortunately I'm wasn't able to find a robust fix
The script I posted above should work as a workaround however.
If there are more reports of JS breaking I'll consider a re-design but I imagine this is a niche issue. Closing for now
Thanks for the report!
