### ISSUE TITLE
Changing the config

### ISSUE THREAD

**Issue by galantra** [Quip13/No-Distractions-Full-Screen#13]
When I try to change the config from Anki's add-on window, I get this errror:

`Invalid configuration: JSONDecodeErrorfExpecting property name enclosed in double quotes: line 2 column 54 (char 55)')`

Furthermore, my config (which I have never explicitly changed, except from Toolbar > View) differs from the default config.

My current config:

```
{
    "MS_Windows_fullscreen_compatibility_mode": true,
    "MS_Windows_fullscreen_force_on_top": false,
    "NDAB_css_v1": ":root {
  --NDABversion: \"1.0\";

  --fontSize: 1.1em;
  --fontVerticalOffset: 1.7em;
  --AnswerButtonHeight: 2.5em;
  --AnswerButtonWidth: 10em;

  --Again_fontColor:#330000;
  --Hard_fontColor:#332200;
  --Good_fontColor:#013300;
  --Easy_fontColor:#000033;

  --Again_fontShadow:#de8181;
  --Hard_fontShadow:#debf81;
  --Good_fontShadow:#81dea2;
  --Easy_fontShadow:#818fde;

  --Again_buttonColor:#ff6961;
  --Hard_buttonColor:#ffa900;
  --Good_buttonColor:#42ff9a;
  --Easy_buttonColor:#61a8ff;

  --default_ease_highlightColor:#8373ff;
}",
    "ND_AnswerBar_enabled": true,
    "_1": "These can be set as desired.",
    "_2": "answer_button_opacity is from 0 (hidden) to 1 (solid). Regardless, mouseover will make answers opaque",
    "_3": "cursor_idle_timer sets how many miliseconds to wait before hiding cursor (negative values mean cursor will not be hidden)",
    "_4": "If settings are subsequently changed through menu buttons, these values will be overwritten and will need to be re-entered",
    "answer_bar_locked": true,
    "answer_bar_posX": "0",
    "answer_bar_posY": "0",
    "answer_button_border_color": "rgba(110, 110, 110, 0.8)",
    "answer_button_border_color_night": "rgba(130, 130, 130, 0.8)",
    "answer_button_border_color_normal": "rgba(200, 200, 200, 0.8)",
    "answer_button_opacity": 0,
    "answer_conf_time": 0.5,
    "auto_toggle_when_reviewing": false,
    "cursor_idle_timer": 10000,
    "do_not_show_NDAB_warning": false,
    "do_not_show_warnings": false,
    "fullscreen_hotkey": "F11",
    "hotkey": "F11",
    "ignore_scroll_on_answer_buttons": true,
    "last_toggle": "full_screen",
    "lock_answer_bar_hotkey": "Ctrl+L",
    "rendering_delay": 300,
    "stay_on_top": false,
    "stay_on_top_windowed": false
}
```

What I get when I press "restore default":

```
{
    "MS_Windows_fullscreen_compatibility_mode": true,
    "NDAB_css_v1": "",
    "ND_AnswerBar_enabled": false,
    "answer_bar_locked": true,
    "answer_bar_posX": 0,
    "answer_bar_posY": 0,
    "answer_button_border_color_night": "rgba(130, 130, 130, 0.8)",
    "answer_button_border_color_normal": "rgba(200, 200, 200, 0.8)",
    "answer_button_opacity": 1,
    "answer_conf_time": 0.5,
    "auto_toggle_when_reviewing": false,
    "cursor_idle_timer": 10000,
    "do_not_show_NDAB_warning": false,
    "fullscreen_hotkey": "F11",
    "last_toggle": "full_screen",
    "lock_answer_bar_hotkey": "Ctrl+L",
    "rendering_delay": 300,
    "stay_on_top_windowed": false
}
```

**Comment by Quip13** [comment]
Yeah the config has changed significantly (I removed a lot of old values and added new ones), and it looks like you've been running NDFS for quite a while.
Anki doesn't delete config values when you update, it just appends new values, so you have a lot of obsolete values. Hitting 'restore default' and deleting the old values that don't do anything makes the config less confusing

Also I would ignore the NDAB_css_V1 value - it's deliberately blank by default and auto-populates when you toggle the no distractions answer bar (if you want to change this value, I would use the settings option with the built in editor)

What value were you trying to change?

**Comment by galantra** [comment]
I tried to change

`  --fontSize: 1.1em;`

Thanks, I didn't know about Anki's appending behavior. I've been running NFDS since the beginning. It really improves my reviewing even more than I expected and I appreciate your idea and its implementation a lot.

I've now just edited _config.json_ manually by replacing its content with the current default config.

**Comment by Quip13** [comment]
Cool - did it work?

**Comment by galantra** [comment]
Wow, thanks for the explanation. It hinted towards the culprit: It seems that https://ankiweb.net/shared/info/112201952 was breaking the config. With it disabled, I can change the config.
