### ISSUE TITLE
Overlap with clickable tags

### ISSUE THREAD

**Issue by bradydjohnson** [Quip13/No-Distractions-Full-Screen#15]
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/6741590/79303994-e5ee4700-7eb5-11ea-998f-e798b89e9b4e.png">
I'm using the AnKingMed deck, and your cool ND buttons are displayed on top of the tags. Is there a way to fix this that doesn't involve changing the cards styling?

**Comment by Quip13** [comment]
Ah unfortunately no but I think Anking has made it easy to shift it up. I think at the top of the styling there's a bit of code you can uncomment (or something like that - I haven't personally used it)

**Comment by Quip13** [comment]
It's mentioned in the description of his youtube vid: https://youtu.be/5XAq0KpU3Jc

Let me know if you can get it working

**Comment by bradydjohnson** [comment]
Thank you! Fixed.
