### ISSUE TITLE
Auto Toggle reverses full-screen when beginning review

### ISSUE THREAD

**Issue by bradydjohnson** [Quip13/No-Distractions-Full-Screen#18]
Sometimes I forget that auto-toggle is enabled and I manually set Anki to full screen. Then when I start reviewing, the auto toggle reverse the full-screen. Is there a way to prevent this?

![ND toggle](https://user-images.githubusercontent.com/6741590/80164792-94257b00-859f-11ea-95f8-8faafae81275.gif)

**Comment by Quip13** [comment]
Thanks for the report and the helpful gif - I tweaked the newest release to avoid this issue.
Should be fixed now - let me know if you're still having issues
