### ISSUE TITLE
Still not getting expected behavior on Mac

### ISSUE THREAD

**Issue by bradydjohnson** [Quip13/No-Distractions-Full-Screen#19]
I'm still not getting the behavior that I think should be happening. 
* When I start reviewing, I thought Auto Toggle would toggle full-screen mode, and it doesn't.
* When I am reviewing in full-screen and I exit full-screen, I thought Auto-Toggle would toggle windowed mode, and it doesn't.

![Kapture 2020-04-28 at 16 32 21](https://user-images.githubusercontent.com/6741590/80539932-fbf80f00-896d-11ea-8054-323a6e0f64b5.gif)

**Comment by Quip13** [comment]
Ah thanks for the report - I see the problem now
Auto-toggle wasn't built to handle the built-in fullscreen mode on Macs (not a feature in Windows), so the program gets confused
I'll need to rethink how to handle fullscreen mode and auto-toggle on OSX

**Comment by Quip13** [comment]
I tweaked the toggle logic and added a new auto-toggle option specific for OSX that should now work predictably.
Of note, the NDFS toggle will no longer change the size of the window - this is now handled by the inbuilt window buttons (or the inbuilt "Enter Full Screen" button in the view menu)
![image](https://user-images.githubusercontent.com/11655350/90056120-5cf0ec00-dcac-11ea-8f0a-dce96b720466.png)

Let me know how it works
