### ISSUE TITLE
Windows taskbar still shows even when full screen is enabled.

### ISSUE THREAD

**Issue by MedicalPotato771** [Quip13/No-Distractions-Full-Screen#2]
Screenshot of problem = https://prnt.sc/rdhllj

Edit: It is fixed, and I don't know how XD

**Comment by MedicalPotato771** [comment]
Okay, this is really weird, I accidentally found out that this happens only when the anki window is maximized, it suddenly worked because I changed the size of the window by mistake. However, it still shows the windows taskbar in full screen mode if enable it when the window i maximized, yeah maximizing the window is definitely what's causing this for me, I've tested it multiple times.

**Comment by Quip13** [comment]
Hey thanks a ton for testing - I appreciate it!
That's interesting - I'm not sure exactly what is causing the issue, but I tweaked some settings to hopefully work better. Can you give this a test and let me know how it goes:
[NDFS_3_2_5_beta](https://github.com/Quip13/No-Distractions-Full-Screen/blob/master/NDFS_3_2_5_beta.ankiaddon)
Just download and run and it should add itself to anki. If maximized -> fullscreen is still giving you issues, can you test out the new config option that enables the old way of doing it? I added an "Advanced Settings" button from the view menu to make getting to the config eaiser
Let me know how it goes

**Comment by Quip13** [comment]
To revert to the old method set
"MS_Windows_fullscreen_compatibility_mode" to false

**Comment by MedicalPotato771** [comment]
Thanks a lot quip, maximized -> fullscreen works perfectly now after the update! And I didn't need to revert to the old method, i.e. "MS_Windows_fullscreen_compatibility_mode" is still true but it works

**Comment by Quip13** [comment]
Ayy good stuff - thanks for the help!
