### ISSUE TITLE
Customise the ND Answer bar

### ISSUE THREAD

**Issue by Willz7** [Quip13/No-Distractions-Full-Screen#20]
Hi @Quip13 awesome add-on, would it be possible to customize the add-on to only show again and good button to help less with distractions?

**Comment by Quip13** [comment]
Ah I'm afraid that's a whole nother can of worms that's beyond the scope of this addon. To maximize compatibility with the myriad of answer button addons, NDFS tries not to change the behavior or appearance of the answer buttons. So if you want to only have 2 buttons I'm afraid you'll need to find another addon to accomplish that. On the plus side anything you find should play well with NDFS.

As a side note, having only 2 buttons is a controversial idea that's been explored in the past, but I think it's safe to say that you would need to carefully rethink the scheduling algorithm to make it effective. Here's some [discussion](https://www.reddit.com/r/Anki/comments/dyo7kr/low_key_anki_worth_it/) and a [blog]( https://massimmersionapproach.com/table-of-contents/anki/low-key-anki/low-key-anki-pass-fail) post on the topic. It might provide some insight into how to go about doing this effectively

Cheers
