### ISSUE TITLE
Slight cutoff for the easy/good/again bar in Anki 2.1.28

### ISSUE THREAD

**Issue by therealdrtahir** [Quip13/No-Distractions-Full-Screen#22]
![image](https://user-images.githubusercontent.com/67523068/88411005-a3130800-cdf0-11ea-9413-591116b9a8c7.png)

I updated to 2.1.28 and saw that in fullscreen mode the bottom bar gets cut off from the left side, hopefully this is something that is easily fixed.

**Comment by Quip13** [comment]
Thanks for the bug report
Could you tell me what zoom addon you are using?
If it is something other than Anki Zoom (https://ankiweb.net/shared/info/538879081), the zoom addon is likely the issue

**Comment by therealdrtahir** [comment]
It is Anki zoom actually.

**Comment by therealdrtahir** [comment]
![image](https://user-images.githubusercontent.com/67523068/88427078-b2ec1580-ce0b-11ea-9e52-bf9856fc898e.png)
These are all my add-ons currently active, the only one left out from this pic cause I couldn't stretch the window enough to show them all was True retention

**Comment by therealdrtahir** [comment]
![image](https://user-images.githubusercontent.com/67523068/88427277-0eb69e80-ce0c-11ea-9b97-0ed146fa56b8.png)
initially it's totally fine
![image](https://user-images.githubusercontent.com/67523068/88427324-21c96e80-ce0c-11ea-9e0b-1a7fea0b7c46.png)
then as soon as you flip the card, it cuts off on the left side.
It would be a lot worse if I had new cards cause then it cuts off the number for them, but rn I don't have any

**Comment by Quip13** [comment]
Ah yeah I'm able to replicate it. I'm not sure what's causing the issue - I suspect it might be something to do with the new built-in zoom functionality
I'll work on a fix

**Comment by therealdrtahir** [comment]
Thank you!
also, the zoom functionality is built in now? does that mean you don't need Anki Zoom?

**Comment by Quip13** [comment]
Not officially I think, but pinch to zoom on a trackpad now zooms without
any add-ons. Hotkeys don't work however

**Comment by Quip13** [comment]
The newest verison of Anki (v2.1.29) seems to have fixed this bug
However this issue seems to be present on old versions of anki (<2.1.15), so I'm still looking into it. But in the meantime updating should fix things

**Comment by therealdrtahir** [comment]
Yeah I updated and saw that too. Guess the issue is sorted(for now). I guess I'll just close this then. Thanks for your help and hard work :)
