### ISSUE TITLE
Hide Answer Bar

### ISSUE THREAD

**Issue by mushakushi** [Quip13/No-Distractions-Full-Screen#23]
Since anki provides shortcut keys for answering the questions. Would it be possible to add a feature that removes the answer bar all together? This way, there would be nothing taking your eyes of your cards. Thanks in advance!

**Comment by ccz-2** [comment]
Under "Answer Bar Visibility" in the menu options you can set the answer bar to be hidden. Note that if you hover your mouse over them they'll appear again, but shortcuts should still work
