### ISSUE TITLE
Strange buttons

### ISSUE THREAD

**Issue by ExtremeCoolDude** [Quip13/No-Distractions-Full-Screen#27]
It was working fine, and suddenly buttons are like this : 
![image](https://user-images.githubusercontent.com/50034073/94199412-7e164080-fed8-11ea-914c-f0b1f6feebc0.png)
![image](https://user-images.githubusercontent.com/50034073/94199991-6a1f0e80-fed9-11ea-94b9-b9a3906661b0.png)

Not a functional issue, but its bugging the crap out of me and makes me pull my hair :D

The buttons are slightly offcenter, and the time frame doesn't appear, and the transparent area around buttons is gone.

I'm not hiding time frame in normal Anki settings though.

Everything latest version. 
Platform : Linux (Manjaro KDE)

Addons :

![image](https://user-images.githubusercontent.com/50034073/94199773-0ac0fe80-fed9-11ea-84f3-4a099897690e.png)

**Comment by ccz-2** [comment]
Ah yeah thanks for the info. Do you remember anything changing that might have caused this? (An add-on update or something?)

Do you mind also disabling all other add-ons and see if the issue persists? Would help me figure out if this is an add-on onflict or an issue with the add-on itself

**Comment by ExtremeCoolDude** [comment]
The issue still persists after disabling all the other addons. I did delete the add on folder and reinstalled it again, but no luck.

**Comment by ExtremeCoolDude** [comment]
{
    box-sizing: content-box;
}
