### ISSUE TITLE
[Suggestion] Automatically enter and leave no distraction mode

### ISSUE THREAD

**Issue by mjuzikfrik** [Quip13/No-Distractions-Full-Screen#3]
Hello,

I'd like to submit a suggestion for an option to automatically enter no distraction mode when going into review panel and automatically leaving it when reviews end or when manually going back to the main menu.

**Comment by Quip13** [comment]
Sure - I'll work on it for the next release

**Comment by mjuzikfrik** [comment]
Great! Looking forward to it. By the way, is there any way to disable the blue rectangle from showing up?

**Comment by Quip13** [comment]
Yes but to preserve maximum compatibility with other addons (are you using the anking button add-on?) I don't want to mess with that area too much. I'd suggest you talk to anking about it

**Comment by Quip13** [comment]
Whenever I inject code to modify existing stuff it can cause unpredictable results especially when it's already being modified by another addon.
As an aside im thinking of possibly building a new bottom bar that just completely replaces the existing one with something more minimalistic.

**Comment by Quip13** [comment]
Added auto-toggle option to latest version!

**Comment by mjuzikfrik** [comment]
Great! :) For some reason it's not working for me properly. It does exits no distraction mode when ending reviews but it doesn't automatically enter the mode when starting reviews. I have to enable it manually.

**Comment by Quip13** [comment]
Interesting - how are you getting to the review screen?
It's written to trigger when you go from the overview screen (screen after you select a deck) to review right now, but it can be more flexible

**Comment by mjuzikfrik** [comment]
Now that you mention it, I do use an addon that let you skip the overview page and go into reviews just by clicking on the deck name. After I disabled that it works perfect. Actually I'm fine with the addon off (the one I mentioed earlier so there's no need to tweak it).

**Comment by Quip13** [comment]
Glad you got it working!

And it shouldn't be too hard of a fix - I'll make it more reliable for next release

**Comment by Quip13** [comment]
FYI the newest version should now be compatible with the skip-overview-screen addon you were probably using (this? https://ankiweb.net/shared/info/1024346707)

**Comment by mjuzikfrik** [comment]
Yes, that's the one. Thanks a bunch. :)
