### ISSUE TITLE
Anki 2.1.50 beta

### ISSUE THREAD

**Issue by mjuzikfrik** [Quip13/No-Distractions-Full-Screen#40]
Hi,

since beta beta 4 I get such an error. I would love to see it fixed.

![Screenshot_1](https://user-images.githubusercontent.com/16630872/156894858-2c1dcf44-f98a-4b30-980e-ac03be7a70b9.png)

**Comment by rwmpelstilzchen** [comment]
It seems @ccz-2 does not maintain this add-on anymore :-(

**Comment by mjuzikfrik** [comment]
Hopefully someone might take over or just straighten out issues that may come in the future with new versions of Anki. For me the addon is a gamechanger.

**Comment by rwmpelstilzchen** [comment]
Yeah. If it means staying with 2.1.49 for the time being, I will do that and not give up this add-on.

IMHO this should be a built-in feature of Anki.

**Comment by mobedoor** [comment]
Potential fix [here](https://github.com/ccz-2/No-Distractions-Full-Screen/issues/39#issuecomment-1103726683)

**Comment by mjuzikfrik** [comment]
It does work, thanks!
