### ISSUE TITLE
Interface goes white when toggled fullscreen

### ISSUE THREAD

**Issue by ExtremeCoolDude** [Quip13/No-Distractions-Full-Screen#7]
![image](https://user-images.githubusercontent.com/50034073/77345350-97d5a000-6d5c-11ea-8a26-b1987a767c92.png)

Anki mac
Version 2.1.23 (de9543ff) 

Add ons:
![image](https://user-images.githubusercontent.com/50034073/77345904-66110900-6d5d-11ea-92a2-8a5543000734.png)

**Comment by Quip13** [comment]
Thanks for the report. Can you try disabling text rendering fix and see if that works?

If it doesn't, the v4.0 beta is designed to avoid these graphical issues, so give that a try:
[NDFS v4.0 beta](https://github.com/Quip13/No-Distractions-Full-Screen/blob/master/NDFS_beta.ankiaddon)
Just download and run. Graphical compatibility with other addons is limited, but should work in the the full release, which hopefully will be coming soon

**Comment by ExtremeCoolDude** [comment]
Using beta versions with no issues so far. Thanks a bunch!
