### ISSUE TITLE
Compatibility with Dancing Baloney

### ISSUE THREAD

**Issue by Cupbox** [Quip13/No-Distractions-Full-Screen#8]
Hi. [Dancing Baloney](https://ankiweb.net/shared/info/378638814) gives theming support to the reviewer screen which does not render in fullscreen.
Could you add compatibility to it?

**Comment by Quip13** [comment]
Thanks for the report.
v4.0 beta is designed to avoid these graphical issues, so give that a try:
[NDFS v4.0 beta](https://github.com/Quip13/No-Distractions-Full-Screen/blob/master/NDFS_beta.ankiaddon)
Just download and run. Graphical compatibility with other addons is limited, but should work in the the full release, which hopefully will be coming soon

**Comment by Cupbox** [comment]
Works perfectly. Thanks again!
